package:
    name: gsps
    version: "1.0.1"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - gbdr
        - pyinotify
        - pyzmq

test:
    imports:
        - gsps
        - gsps.cli
        - gsps.processor
    commands:
        - gsps-cli -h

about:
    home: https://github.com/axiom-data-science/GSPS
    license: MIT License
    summary: 'Watches a directory for new *db flight/science files and publishes the data to a ZeroMQ socket.'
